environment-lock.yml
environment.yml

Fixes bug with wms layer creation in pyqgis

Upgrade qgis to v3.10.7

---

.bumpversion.cfg
CHANGELOG.md
README.md
qgreenland/__init__.py
qgreenland/assets/styles/arctic_vegetation_biomass.qml
qgreenland/config/datasets.yml
qgreenland/config/layers.yml
qgreenland/config/schema/datasets.yml
qgreenland/tasks/common/fetch.py
qgreenland/tasks/layers/__init__.py
qgreenland/tasks/layers/arctic_vegetation.py
qgreenland/util/cmr.py

Add Circumpolar Arctic Vegetation Biomass layer

Arctic vegetation

---

qgreenland/config/layers.yml
qgreenland/test/util/test_qgis.py

This is really complex and needs a careful review

Add BedMachine "error" layer

---

qgreenland/config/layers.yml

@trey-stafford don't actually review this, please feel better!

Change Febuary -> February

---

qgreenland/assets/styles/airport_point.qml
qgreenland/assets/styles/education_facility_point.qml
qgreenland/assets/styles/financial_facility_point.qml
qgreenland/assets/styles/health_facility_point.qml
qgreenland/assets/styles/seaport_point.qml
qgreenland/config/datasets.yml
qgreenland/config/layers.yml

Add datasets sourced from Humanitarian Data Exchange

---

qgreenland/assets/styles/buildings_shape.qml
qgreenland/assets/styles/hotosm_populated_places_point.qml
qgreenland/assets/styles/roads_line.qml
qgreenland/config/layers.yml

- Populated places: Scale-dependent rendering for different classes of
places (and labels)
- Roads: Modified QGIS topo_road with labels
- Buildings: Add labels

Add new hotosm layer styles

---

scripts/cleanup_input_cache.py

This was super frustrating. I know this could be done better, but I need to prioritize other work. This is good enough for now.

Hacky script to get a list of dirs to remove. Needs work.

---

qgreenland/config/datasets.yml
qgreenland/config/layers.yml

Layer title capitalization and date standardization

Matt checklist fixups

---

Dockerfile
environment.yml

Attempting to resolve the issue with jobs "not granted run permission by
the scheduler", e.g.:
* 1013 were left pending, among these:
* 1013 was not granted run permission by the scheduler:
We have no idea what causes this so this is a shot in the dark.

Upgrade Luigi to 3.x

---

qgreenland/config/layers.yml
scripts/private-archive-preprocess/esa_cci_gravimetric_mass_balance_dtu/gmb_dtu_nc_to_gpkg.py

TODO: Push private archive data to prod

Fix pre-processing to use start/end dates instead of `t`

---

qgreenland/config/datasets.yml

Update RACMO description, place names, and remove several TBDs and TODOs.

Update RACMO etc.

---

qgreenland/config/layers.yml
qgreenland/tasks/common/misc.py
qgreenland/util/misc.py

I thought we fixed this already -- did we mess up a merge?

Fix ExtractNcDataset job

---

qgreenland/assets/styles/seismograph_stations.qml
qgreenland/config/layers.yml

Add style for seismograph stations

---

.bumpversion.cfg
qgreenland/__init__.py
qgreenland/assets/styles/wmm_contours.qml
qgreenland/config/layers.yml

TODO: Populate SQL for all WMM years. Only 2020 done so far. Any way to DRY out SQL? Tablenames are the driver of repeated config.

WMM styles

---

qgreenland/config/datasets.yml
qgreenland/config/layers.yml

Corrections from read through of datasets.yml and layers.yml

Picky edits

---

CHANGELOG.md
qgreenland/assets/styles/greenland_coastline.qml
qgreenland/config/layer_groups.yml
qgreenland/config/layers.yml

Update qgreenland coastline style to semitransparent fill

---

environment.gdal.yml
qgreenland/constants.py
qgreenland/util/luigi/tasks/main.py
qgreenland/util/luigi/tasks/pipeline.py
qgreenland/util/misc.py
scripts/experimental/plugin_manifest/docker-compose.yml
scripts/experimental/plugin_manifest/prepare_layers.sh

Output layers to `RELEASES_DIR / 'layers' / layer_id`, then zip them up. Used hardlinks to save on WIP disk space.

Plugin server structure

---

scripts/cleanup.sh
scripts/cli.sh
scripts/container_cli.sh
scripts/dev_run_task.sh

Readlink on OSX is different from Linux

Readlink fix

---

qgreenland/config/cfg-lock.json
qgreenland/config/layers/Geophysics/Heat flux/geothermal_heat_flux.py

The new URL for this layer downloads a .nc file instead of a .zip.
Fixup layer steps for geothermal heat flux

Fixup layer steps for geothermal heat flux

---

qgreenland/models/config/layer.py
qgreenland/util/qgis/layer.py

validate style in layer model

---

CHANGELOG.md
qgreenland/ancillary/styles/transparent_labeled_shape.qml
qgreenland/config/cfg-lock.json
qgreenland/config/layers/Reference/timezones.py
qgreenland/config/layers/Reference/utm_zones.py

Timezone labels

---

qgreenland/ancillary/styles/greenland_coastline.qml

Twila preferred the line slightly thinner!

Slightly thinner coastline

---

CHANGELOG.md
qgreenland/config/cfg-lock.json
qgreenland/config/layers/Glaciology/Ice sheet velocity/ITS_LIVE/layers.py
qgreenland/config/layers/Terrain models/arctic_dem.py

Set up some of the first plugin-only layers.

Plugin only layers

---

qgreenland/config/cfg-lock.json
qgreenland/config/layers/Glaciology/Surface elevation change/__settings__.py

Display surface elevation error on top of observed.

Reorder surface elevation change

---

doc/CONTRIBUTING.md

Document the new storage directory structure

Document the new storage directory structure

---

qgreenland/config/cfg-lock.json
qgreenland/config/helpers/layers/esa_cci_surface_elev.py
qgreenland/config/helpers/steps/build_overviews.py
qgreenland/config/helpers/steps/compress_and_add_overviews.py
qgreenland/config/helpers/steps/compress_raster.py
qgreenland/config/layers/Biology/Vegetation/biomass.py
qgreenland/config/layers/Glaciology/Ice sheet velocity/ITS_LIVE/layers.py
qgreenland/config/layers/Oceanography/Seawater temperature 2018 (25km)/woa2018.py

Use prediction to compress rasters more better

Some raster predictor updates

---

qgreenland/cli/__init__.py
qgreenland/cli/provenance.py
qgreenland/util/luigi/tasks/main.py
qgreenland/util/provenance.py

Add a `provenance` CLI command.

Add provenance CLI utility

---

qgreenland/cli/__init__.py
qgreenland/cli/fetch.py
qgreenland/cli/layers.py
qgreenland/cli/provenance.py
qgreenland/util/luigi/tasks/main.py
qgreenland/util/provenance.py

Layerlist cli

---

.bumpversion.cfg
CHANGELOG.md
CITATION.cff
qgreenland/__init__.py
qgreenland/_typing.py
qgreenland/config/cfg-lock.json
qgreenland/config/helpers/steps/compress_and_add_overviews.py
qgreenland/config/layers/Basemaps/background.py

- Add JPEG support to raster compression helper
- Compress background layer with JPEG

Add JPEG compression support

---

qgreenland/config/cfg-lock.json
qgreenland/config/datasets/arctic_vegetation_biomass.py

Fix vegetation biomass; the old concept ID was deleted due to a cloud migration process.

Fix vegetation biomass CMR configuration

---

qgreenland/cli/provenance.py
qgreenland/config/cfg-lock.json
qgreenland/config/datasets/nunagis_protected_areas.py
qgreenland/config/datasets/political_boundaries.py
qgreenland/models/config/asset.py
qgreenland/models/config/step.py
qgreenland/util/luigi/__init__.py
qgreenland/util/luigi/tasks/fetch.py
qgreenland/util/provenance.py

Add fetch behavior to provenance information

Add fetch behavior to provenance information

---

qgreenland/models/config/asset.py
qgreenland/util/provenance.py

Fixup fetch provenance repr-style output

Fixup fetch provenance repr-style output

---

qgreenland/config/cfg-lock.json
qgreenland/config/helpers/assets/ogr_remote.py

Fixup ogr remote asset cmd

---

doc/conf.py
scripts/experimental/build_docs_on_change.sh

Autodoc config / lint

---

doc/contributor-how-to/contribute-styles.md
doc/index.rst
doc/reference/glossary/contributor-glossary.md
doc/reference/glossary/user-glossary.md

Front-load docs with "What is QGreenland?"

Front-load docs with "What is QGreenland?"

---

doc/conf.py
doc/reference/api/models.md

Add source code links to docs

---

doc/conf.py

Trivial comment

---

doc/Makefile
doc/index.rst
scripts/experimental/build_docs_on_change.sh

Sphinx warnings as errors

---

doc/index.rst

These weren't really doing anything

Remove indices and tables from docs

---

qgreenland/util/luigi/tasks/pipeline.py

Fix incorrect ancillary file source filepath

Fix incorrect ancillary file source filepath

---

CHANGELOG.md
README.md
doc/contributing.md
environment-lock.yml
environment.yml
qgreenland/util/luigi/tasks/pipeline.py

Convert markdown to HTML when adding documents to package

Convert markdown to HTML when adding documents to package

---

.readthedocs.yaml

Remove epub doc format

---

doc/acknowledgements.md

Add cmocean acknowledgement

---

doc/Makefile
doc/conf.py
doc/index.rst
doc/reference/cli/index.rst
doc/requirements.txt
environment.yml
qgreenland/cli/fetch.py
qgreenland/cli/layers.py
qgreenland/cli/provenance.py
qgreenland/cli/run.py
scripts/experimental/build_docs_on_change.sh

CLI documentation

---

qgreenland/cli/cleanup.py
qgreenland/cli/fetch.py
qgreenland/cli/layers.py
qgreenland/cli/provenance.py
qgreenland/cli/run.py
qgreenland/util/luigi/tasks/pipeline.py
qgreenland/util/qgis/project.py

- QGZ project file
- Improve safety of dev cleanup
- Better code comments
- Fix issue with `contributing.md` ancillary file

Qgz project file

---

Dockerfile
doc/Makefile
doc/conf.py
environment-lock.yml
environment.yml
qgreenland/util/command.py
qgreenland/util/luigi/tasks/pipeline.py

Sphinx pdf in package

---

doc/contributor-how-to/contribute-layers.md

Add documentation to the contributing new layers doc. I had much more but it started looking like a tutorial, so I left what I thought was necessary 
- [X ] Config lockfile updated (`inv config.export > qgreenland/config/cfg-lock.json`)
- [X ] Version bumped if needed (`bumpversion (major|minor|patch|prerelease|build`)
- [X ] CHANGELOG.md updated
- [X ] Documentation updated if needed
- [X ] New unit tests if needed

Contributor how to

---

doc/contributor-how-to/write-documentation.md
doc/what_is_qgr.md

Document how to write documentation

Document how to write documentation

---

doc/citing.md
doc/reference/glossary/user-glossary.md
doc/what_is_qgr.md

Link to plugin docs

---

CHANGELOG.md
qgreenland/ancillary/styles/wdmam.qml
qgreenland/config/cfg-lock.json
qgreenland/config/datasets/wdmam.py
qgreenland/config/layers/Geophysics/wdmam.py

New plugin-only layer representing magnetic anomalies in nanoTesa as points.

QGR-46 Add World Digital Magnetic Anomaly Map layer

---

doc/reference/online-resources.md
doc/user-how-to/online-layers.md

Reference document for various online services (WMS, WFS, WCS) that users can add to QGIS.

QGR-47 Online layers ref doc

---

doc/user-how-to/troubleshooting.md

Tell the user to reboot after changing ulimit settings, and mention the "Too many connections" error as well.

Improve existing troubleshooting question, add a new one

---

doc/discussion/about_project.md
doc/user-how-to/troubleshooting.md

Migrate FAQs from website to RTD

Migrate FAQs from website to RTD

---

CHANGELOG.md
qgreenland/ancillary/styles/albedo.qml
qgreenland/config/cfg-lock.json
qgreenland/config/datasets/albedo.py
qgreenland/config/layers/Geophysics/Albedo/albedo.py

Monthly albedo data from sentinel-3 for 2018-07 and 2019-07.

Add monthly albedo data from Sentinel-3

---

.bumpversion.cfg
CHANGELOG.md
CITATION.cff
doc/conf.py
doc/tutorials/get-started.md
doc/user-how-to/troubleshooting.md
qgreenland/__init__.py
qgreenland/util/luigi/tasks/pipeline.py

Switch back to `.qgs` project file

Switch back to `.qgs` project file

---

qgreenland/ancillary/templates/layer_cfg.py
qgreenland/config/datasets/earthquakes.py

Add in_package and comment to remind users to add new layer to QGreenland Custom

add in_package to layer config template

---

qgreenland/config/datasets/earthquakes.py

Update earthquake layer for 2021 data

---

doc/user-how-to/adding-data.md

transfer section 6 content from user manual

How-to adding new datasets to QGreenland

---

doc/user-how-to/plugin-how-to.md

Add note explaining QGreenland Custom storage location/downloading data

Add note to user plugin how-to

---

doc/user-how-to/troubleshooting.md

Add troubleshooting from the user manual that doesn't already exist on readthedocs

Add additional troubleshooting from user manual

---

doc/reference/glossary/user-glossary.md

Add terms to readthedocs glossary from user manual

Add terms to readthedocs glossary from user manual

---

doc/what_is_qgr.md

add link to qgr website

---

doc/tutorials/interacting-with-geospatial-data.md

Edit Spatial Data Overview content

Edit Spatial Data Overview content

---

doc/tutorials/plugin-how-to.md

move user how to plugin to tutorial section

---

README.md
doc/citing.md
doc/contributor-how-to/release-new-version.md
doc/contributor-how-to/run-qgreenland.md
doc/contributor-how-to/troubleshooting.md
doc/tutorials/get-started.md
doc/tutorials/interacting-with-geospatial-data.md
doc/what_is_qgr.md

Update and fix content in readthedocs to prepare for v2.0.0

Readthedocs content updates

---

doc/contributor-how-to/how-to-dev-plugin.md
doc/index.rst
doc/reference/architecture/configuration.md
doc/reference/glossary/index.rst
doc/tutorials/plugin-how-to.md
doc/what_is_qgr.md
qgreenland/util/luigi/tasks/pipeline.py

Make updates to v2.0 package items

---

doc/index.rst
tasks/docs.py

Support generating pdf docs in `invoke docs.build`

---

doc/user-how-to/arctic-dem.md

Added website link for qgreenland.org/download. Small other working changes.
[ANYTHING ON THIS LIST NEED DOING?]

edit arctic dem how-to

---

doc/index.rst
doc/tutorials/video-series-overview.md

Make session headers links to the video

---

doc/user-how-to/metadata.md

Small edits to the metadata tutorial text.

Small text edits

---

doc/contributor-how-to/write-documentation.md

Add section to our documentation about QGIS theme in contributor how-to for writing documentation.

Add section about QGIS theme in contrib how-to

---

README.md
doc/discussion/contributing.md
doc/reference/data-compatibility-guide.md
doc/tutorials/plugin-how-to.md

Other doc fixups

---

doc/tutorials/video-series-overview.md

Updates to tutorial video overview

update tutorial overview

---

.bumpversion.cfg
CHANGELOG.md
CITATION.cff
doc/conf.py
qgreenland/__init__.py

We had branched to do some hacks to the documentation for v2.0.0 final release. But the version metadata changes didn't make it back to `main`.

Update version metadata

---

CHANGELOG.md
qgreenland/config/cfg-lock.json
qgreenland/config/datasets/bedmachine.py
qgreenland/config/layers/Terrain models/BedMachine/bedmachine.py

Update bedmachine dataset to v5

---

CHANGELOG.md
qgreenland/config/cfg-lock.json
qgreenland/config/datasets/seaice.py
qgreenland/config/helpers/ancillary/sea_ice_age_params.json
scripts/data/make_sea_ice_age_params.py

2022 is not available yet but should be soon.

Update sea ice age layers from 2010-2020 -> 2011-2021

---

CHANGELOG.md
qgreenland/config/cfg-lock.json
qgreenland/config/helpers/layers/sea_ice_concentration.py
qgreenland/config/layers/Sea ice/Monthly mean concentration (25 km)/Feb or March (max monthly extent)/__settings__.py

Update sea ice concentration layers to 2011-2022

---

CHANGELOG.md
qgreenland/ancillary/styles/buildings_shape.qml
qgreenland/config/cfg-lock.json
qgreenland/config/datasets/asiaq_nunagis.py
qgreenland/config/layers/Places/__settings__.py
qgreenland/config/layers/Places/buildings.py

Add buildings layer from Asiaq/NunaGIS

---

qgreenland/config/cfg-lock.json
qgreenland/config/layers/Internet-required data/__settings__.py
qgreenland/config/layers/Internet-required data/online.py

Fixup bad spelling (`relif` -> `relief`) in layer id

---

qgreenland/models/config/layer.py

Should have included this in the last PR. Shame on me! :)

Add useful documentation around font validation code

---

qgreenland/ancillary/styles/racmo_grounded_ice.qml
qgreenland/config/cfg-lock.json
qgreenland/config/helpers/layers/racmo.py

Ensure all palletted styles have descriptive labels for each value

---

CITATION.cff

Add our NSF grant number to our CITATION.cff metadata
checkbox.

Specify grant funding source in metadata

---

CHANGELOG.md
qgreenland/config/cfg-lock.json
qgreenland/config/datasets/online.py
qgreenland/config/layers/Internet-required data/__settings__.py
qgreenland/config/layers/Internet-required data/online.py

WMS config for GEUS geological map. Addresses #566. We originally hoped to add the data itself to QGreenland, but it had some issues that made it difficult for us to add.  
checkbox.

Online-only GEUS geological map

---

CHANGELOG.md
qgreenland/ancillary/styles/mineral_occurrences.qml
qgreenland/config/cfg-lock.json
qgreenland/config/datasets/geus_mineral_occurrences.py
qgreenland/config/layers/Geology/__settings__.py
qgreenland/config/layers/Geology/minerals.py

Title. Closes #624.
This layer is about 1.3M on disk. I think this is fine, but we could also add this as just an online-only (WFS) resources if we prefer.
checkbox.

Add mineral occurrences layer from GEUS

---

doc/contributor/reference/architecture/serving-data.md
scripts/analyze_logs.py

Add docstring for the `analyze_logs.py` script w/ usage instructions. Add new doc page for how qgreenland core is served.
checkbox.

Docstring for logs script

---

doc/user/discussion/what-is-next-qgreenland.md

Related to #680. Title. 
checkbox.

Add user discussion documentation for what's next for qgr

---

doc/conf.py
doc/disclaimer.md
doc/user/tutorials/analyze-ice-sheet-volume.md
doc/user/tutorials/create-print-layout.md
doc/user/tutorials/get-started.md
doc/user/tutorials/interacting-with-geospatial-data.md

Update tutorial docs for accuracy.
checkbox.

Trey tutorial docs updates

---

doc/user/discussion/what-is-next-qgreenland.md

These break the PDF build. The process hangs, waiting for user input:
```
! LaTeX Error: Unknown graphics extension: .svg.
See the LaTeX manual or LaTeX Companion for explanation.
Type  H <return>  for immediate help.
...
l.2917 ...9b58e00623a9fa197/NSF-1928393-red}.svg}}
%
?
```
checkbox.

Remove NSF badges from "what is next for qgreenland" discussion

---

doc/user/reference/glossary.md

Just one minor change.
checkbox.

Update user reference docs

---

qgreenland/config/cfg-lock.json
qgreenland/config/layers/Glaciology/Ice sheet velocity/GrIMP/grimp.py

Title. This raises an error during processing.
checkbox.

Revert use of sed

---

CHANGELOG.md

Closes #756 
cc @twilamoon-science 
checkbox.

Aggregate v3 changelog

---

qgreenland/config/cfg-lock.json

title. Resolves #760 and #765 CI errors
checkbox.

Lock config

---

doc/user/discussion/about_project.md

Update user discussions docs

---

CHANGELOG.md
qgreenland/config/cfg-lock.json
qgreenland/config/datasets/geothermal_heat_flow.py
qgreenland/config/layers/Geophysics/Heat flux/Heat flow (Colgan et al.)/geothermal_heat_flow.py

Update heat flow layer metadata. Closes #744 
checkbox.

Heat flow layer title and metadata updates

---

doc/conf.py

Update doc authors

---

doc/acknowledgements.md

Fixup open source acknowledgements reference to `environment-lock.yml`

---

README.md

Update README annoucement to indicate release of v3 :tada:

---

doc/citing.md

Add DOIs to QGreenland citations on ReadTheDocs. <https://qgreenland.readthedocs.io/en/latest/citing.html>
checkbox.

Add DOIs to citations on RTD
