- CHANGELOG.md
- docker-compose.yml
- qgreenland/__init__.py
- qgreenland/constants.py
- qgreenland/tasks/main.py
- qgreenland/util/misc.py
- qgreenland/util/qgis.py
We can worry about performance in the future. For now, we want to be sure that our releases don't interfere with each other, so we set up the workflow to be environment-gnostic and do cleanup in non-dev environments. Devs are capable of cleaning up after themselves as-necessary with the cleanup script. Also for the future, we could make that cleanup script smarter/take arguments.
> Aggresively cleanup intermediate files in non-dev environments

- qgreenland/config/layers.yml
The bedmachine netcdf dataset that we create these layers from have a `source`
attribute. Include that information in the layer description.
> Add 'source' to bedmachine layer descriptions.

- qgreenland/config/layers.yml
- qgreenland/tasks/common/vector.py
- qgreenland/util/vector.py
Shapefiles have a few issues, but the one that caused us to do this was the
limitation on how long field names could be. Some field names were being
truncated. E.g., with the gc-net layer, "Station Number" becomes "Station Nu"
and "Transmitter" becomes "Transmitte"
> Use geopackages for vectors in QGreenland instead of shapefiles

- CHANGELOG.md
- qgreenland/constants.py
- qgreenland/tasks/main.py
Now when a user unzips the package, the name of the extracted dir is the same
name as the zip archive.
This prevents the possibility of someone e.g. downloading a newer version of
QGreenland that gets unpacked into an older version.
> Zipped QGreenland package's root dir is named same as package.

- qgreenland/assets/local_data/arctic_circle.geojson
- qgreenland/assets/styles/arctic_circle.qml
- qgreenland/config/layers.yml
The label currently reads:
> Arctic Circle (66.56667 degrees North)
This is pulled from the `Name` attribute in our `arctic_circle.geojson` file. Is this OK, or should we change this to e.g., `Arctic Circle (66° 34' North)`?
> Add arctic circle style

- CHANGELOG.md
- qgreenland/config/layers.yml
> Avoid special chars `>` and `:` in layer titles

- qgreenland/util/luigi/target.py
This will allow us to safely ctrl-c to stop execution and still have the tmp dir
created by `temporary_path_dir` get cleaned up.
> Catch `KeyboardInterrupt` in `temporary_path_dir` and cleanup

- nginx/Dockerfile
Fix nginx index page from a default `index.html` to an autoindex of our mounted volumes (layers, packages).
> Allow nginx to index layers and packages

- qgreenland/config/cfg-lock.json
- qgreenland/config/helpers/layers/geological_map.py
Fix capitalization issue with geology layer. Did this layer succeed in the past because of OSX's case-insensitive filesystem?
> Fix capitalization issue with onshore_planar layer

- CHANGELOG.md
- qgreenland/config/cfg-lock.json
- qgreenland/config/datasets/seaice.py
- qgreenland/config/helpers/layers/sea_ice_concentration.py
Update the sea ice index dataset to include min/max concentrations from 2021.
Note that sea ice age data for 2021 is not available for NSIDC-0611 until the start of next year. There is 'near real time' data available via NSIDC-0749, but I think we should just wait until the next update to NSIDC-0611 to include that data.
> Update seaice index

- CHANGELOG.md
- qgreenland/ancillary/styles/racmo_runoff.qml
Switch RACMO runoff layer to use viridis and make `0` values transparent.
> Update RACMO runoff style

- CHANGELOG.md
- qgreenland/ancillary/styles/greenland_coastline.qml
Remove green tint, thicken outline
Make the coastline layer (default enabled) look better. Remove green tint, thicken lines.
> Update coastline style

- qgreenland/config/cfg-lock.json
- qgreenland/config/layers/Terrain models/arctic_dem.py
Clarify the Arctic DEM layer's symbology in the description. Some users reported confusion that we provided hillshade imagery instead of the actual data. In fact, we did provide the actual data, and QGIS stylized it as hillshade. Should we simply avoid hillshade? Is there a way to create a "virtual copy" of a layer with a different style, so a layer could be delivered with two styles to make this clearer?
> Note symbology in Arctic DEM layer

- qgreenland/cli/cleanup.py
Cleanup the code, too!
Enable cleaning up released layers by pattern.
> Add the ability to cleanup release layers by pattern

- qgreenland/cli/cleanup.py
- qgreenland/cli/run.py
- qgreenland/util/luigi/tasks/pipeline.py
Sometimes you want to run the whole pipeline without zipping in dev. `-Z` does that now. 
> CLI flag to run without zipping

- CHANGELOG.md
- qgreenland/config/cfg-lock.json
- qgreenland/config/helpers/layers/racmo.py
Cast RACMO promice masks to `Byte`.
> Byte type promice mask

- CHANGELOG.md
- qgreenland/config/cfg-lock.json
- qgreenland/config/layers/Glaciology/basal_thermal_state.py
Cast basal thermal state layer to Int16. Saves us an entire **71KB**!
> Int for basal thermal state

- CHANGELOG.md
- qgreenland/test/util/test_metadata.py
- qgreenland/test/util/test_qgis.py
- qgreenland/util/config/export.py
- qgreenland/util/luigi/tasks/main.py
- qgreenland/util/metadata.py
- qgreenland/util/provenance.py
- qgreenland/util/qgis/layer.py
- qgreenland/util/qgis/metadata.py
Export layer metadata (abstract info; description, citation, etc) to a `metadata.txt` file that sits alongside layer data in the final layer dir. This allows users who are browsing layers e.g., in their filesystem, to quickly access relevant information.
> Export layer metadata txt

- qgreenland/config/cfg-lock.json
- qgreenland/config/datasets/nunagis_protected_areas.py
- qgreenland/config/datasets/political_boundaries.py
- qgreenland/config/helpers/assets/ogr_remote.py
- qgreenland/models/config/asset.py
- qgreenland/util/luigi/__init__.py
- qgreenland/util/luigi/tasks/fetch.py
Replace usage of `OgrRemoteAsset` with `CommandAsset`
> Replace usage of `OgrRemoteAsset` with `CommandAsset`

- qgreenland/config/cfg-lock.json
- qgreenland/config/layers/Basemaps/background.py
Fixup JPEG compression artifacts for the background layer by using a mask band.
> Fixup JPEG compression artifacts for the background layer 

- doc/reference/architecture/configuration.md
Cross-reference pydantic models in configuration docs
> Cross-reference pydantic models in configuration docs

- doc/conf.py
- doc/reference/architecture/configuration.md
Use `extlinks` to DRY out external refs to github
> Use `extlinks` to DRY out external refs to github

- qgreenland/util/model_validators.py
Fix paragraph text validator to handle empty strings.
It still doesn't tell you which file or which line the error came from, but that's a separate problem.
> Fix paragraph text validator to handle empty strings

- doc/acknowledgements.md
- doc/citing.md
- doc/conf.py
- doc/index.rst
- doc/what_is_qgr.md
- Clean up OBE acknowledgements
- Improve PDF output
- Nest all `toctree`s under a common header. This is important or the first chapter header gets swallowed and treated as the header for the whole document.
- Conditional content for HTML site only
- Add "parts" to the LaTeX / HTML output
- Tweak LaTeX rendering options: enable pagerefs, URL footers, remove blank pages
- Remove JSON schema output from all doc outputs. It was overwhelming in PDF form, and I don't know how to only display them in HTML cleanly.
> PDF documentation improvements

- CHANGELOG.md
- qgreenland/config/cfg-lock.json
- qgreenland/config/helpers/layers/wmm.py
- qgreenland/config/layers/Geophysics/World Magnetic Model/Geomagnetic coordinates 2020/geomagnetic_coordinates.py
Remove most wmm layers from the core zip pacakge.
Feedback from Lu suggests most of these layers are not too useful. Keep dip poles, main field declination, and blackout zones in the qgreenland core package for now. The rest will continue to be available via the plugin!
> Remove wmm layers from core

- docker-compose.yml
- scripts/experimental/release_postprocessing.sh
More NFS hackarounds: Add a sync script and add hack to docker-compose
> More NFS hackarounds

- CHANGELOG.md
- qgreenland/test/util/config/test_config_export.py
- qgreenland/util/config/export.py
Remove online layers from plugin manifest.json file. Online layers will be re-added to the manifest once the plugin has support for online layers
> Temporarily remove online layers from manifset.json

- qgreenland/config/cfg-lock.json
- qgreenland/config/helpers/layers/sea_ice_concentration.py
fix max_concentration_year variable since March 2022 data is not available
> fix max_concentration_year variable

- doc/index.rst
- qgreenland/util/luigi/tasks/pipeline.py
Spit "Reference" section in docs into 'contributor' and 'user' sections so that we can only include the 'user' reference in the pdf included in the qgreenland core package.
> Splitup reference section into 'user' and 'contributor' sections.

- qgreenland/config/cfg-lock.json
- qgreenland/config/layers/Geophysics/Heat flux/Heat flow (Colgan et al.)/geothermal_heat_flow.py
Update filename for a geothermal_heat_flow_map file causing an error in QA build
> Fix geothermal_heat_flow_map filename

- Dockerfile
- environment-lock.yml
- environment.yml
Update Docker micromamba version to v1.2.0. Update `mamba` version that installs dependencies to docker image to ~=v1.2.0.
> Update mamba / micromamba in Docker image

- .mypy.ini
- environment-lock.yml
- environment.yml
Upgrade python to 3.10
We'll have to hold off on upgrading to python 3.11 until invoke v2.0 is released on conda-forge. Although invoke v1 can be installed with python v3.11, attempts to use it result in an error. See: https://github.com/pyinvoke/invoke/issues/891
> Update python version to v3.10

- qgreenland/util/luigi/tasks/pipeline.py
Use kwargs instead of positional arguments to make code more readable
> Pass keyword args to shutil.make_archive

- scripts/analyze_logs.py
At the end of each log analysis report, print out an aggregation of all versions grouped by major version.
> Add quick-and-dirty aggregation methods to log analysis script

- Dockerfile
- doc/conf.py
- doc/contributor-how-to/run-qgreenland.md
- docker-compose.yml
- qgreenland/cli/__init__.py
- qgreenland/cli/version.py
- qgreenland/constants/paths.py
On any CLI command: `fatal: detected dubious ownership in repository at /luigi/tasks/qgreenland`
This is because we're running a `git` command on a repository that's volume mounted and could be owned by anyone (IMO we should re-visit this choice. Why is code being volume-mounted in in non-dev scenarios?). It wasn't happening before because this is a new check in Git >2.35.
It happens on any CLI command because our `constants.paths` import runs a Git command to determine the version of QGreenland to build a path. This is a problem in itself, and we have a pre-existing TODO to address it, but it's not relevant to the root problem; even if the error isn't triggered on any CLI command, it would be triggered when our code did eventually generate a version string using Git.
* Added a `version` …
> Fix Git error when using CLI: `fatal: detected dubious ownership in repository`

- CHANGELOG.md
- qgreenland/config/cfg-lock.json
- qgreenland/config/datasets/geothermal_heat_flow.py
- qgreenland/config/layers/Geophysics/Heat flux/Heat flow (Colgan et al.)/geothermal_heat_flow.py
Upgrade to v2 of the Colgan et al. geothermal heat flux dataset. Links to v1 data were broken.
> Update geothermal heat flux dataset (Colgan et al.) to v2

- Dockerfile
Not sure exactly what's happening here, but without this change, we get this error when trying to run the image:
```
Traceback (most recent call last):
File "/opt/conda/bin/mamba", line 7, in <module>
from mamba.mamba import main
ModuleNotFoundError: No module named 'mamba'
```
> When the conda lock file is installed after mamba, mamba gets removed.

- CHANGELOG.md
- qgreenland/ancillary/styles/roads_line.qml
- qgreenland/config/cfg-lock.json
- qgreenland/config/datasets/asiaq_nunagis.py
- qgreenland/config/layers/Places/__settings__.py
- qgreenland/config/layers/Places/roads.py
Add roads layer from Asiaq/NunaGIS.
> Asiaq nunagis roads layer

- CHANGELOG.md
- qgreenland/ancillary/styles/buildings_shape.qml
- qgreenland/ancillary/styles/roads_line.qml
- qgreenland/config/cfg-lock.json
- qgreenland/config/datasets/asiaq_nunagis.py
- qgreenland/config/layers/Places/__settings__.py
- qgreenland/config/layers/Places/buildings.py
- qgreenland/config/layers/Places/roads.py
Composed of PRs:
* #568 
* #569
Under consideration:
* #570
> Asiaq nunagis layers

- CHANGELOG.md
- qgreenland/config/cfg-lock.json
- qgreenland/config/datasets/esa_cci.py
- qgreenland/config/helpers/layers/esa_cci_surface_elev.py
- scripts/private-archive-preprocess/esa_cci_surface_elevation_change/preprocess.sh
This PR updates the "Glaciology/Surface elevation change" layers to the latest version
(v3) of the Climate Change Initiative (CCI) Surface Elevation Change dataset
from the European Space Agency (ESA). This extends the timeseries to include a
surface elevation change layer for 2016-2020.
> Update the ESA CCI Surface Elevation Change layers

- qgreenland/config/cfg-lock.json
- qgreenland/config/datasets/asiaq_nunagis.py
Based on feedback from Frederik at Asiaq. He informed us that we should primarily credit Asiaq, as they "are responsible for producing and maintaining these datasets".
> Update citation for asiaq nunagis layers

- CHANGELOG.md
- qgreenland/config/cfg-lock.json
- qgreenland/config/layers/Oceanography/Bathymetry/bathymetric_chart.py
This PR removes the "Oceanography/Bathymetry/Depth contours" layer. 
This layer was pulled from the "Geological map of the Arctic / Carte gologique
de l'Arctique" (Harrison et al., 2011) dataset and was provided with the
geological data for additional context. It was derived from the (IBCAO)
grid. Comparing this with the current IBCAO and GEBCO grids, these contours seem
outdated. They also only cover a portion of QGreenland's background
extent. Users can produce their own custom contour layer from the included
"Oceanography/Bathymetry/Depth (400m)" layer using the Processing Toolbox (GDAL
-> Raster extraction -> Contour).
This PR supersedes https://github.com/nsidc/qgreenland/pull/586 
> Remove "Oceanography/Bathymetry/Depth contours" layer

- CHANGELOG.md
- qgreenland/config/cfg-lock.json
- qgreenland/config/datasets/promice_stations.py
- qgreenland/config/layers/Human activity/Research sites/__settings__.py
- qgreenland/config/layers/Human activity/Research sites/promice_research_stations.py
Title.
Our current station locations for PROMICE and GC-NET layers is from the [map_GC-Net_PROMICE_kml](https://github.com/GEUS-Glaciology-and-Climate/map_GC-Net_PROMICE_kml) GitHub repo, which used "2017-2018 average of station GPS data" for station locations.
New stations have been added. [The PROMICE and GC-Net automated weather station data in Greenland](https://dataverse.geus.dk/dataset.xhtml?persistentId=doi:10.22008/FK2/IW73UU) dataset from GEUS includes a `AWS_metadata.csv` with location data for stations  (published May 2023 w/ citation indicating 2022; the last station added in the  `AWS_metadata.csv` is QAS_Lv3 on 2022-08-29)
> Update PROMICE/GC-NET layers to use newer dataset from GEUS

- CHANGELOG.md
- qgreenland/ancillary/styles/arctic_vegetation.qml
- qgreenland/config/cfg-lock.json
- qgreenland/config/datasets/circumpolar_arctic_vegetation_map.py
- qgreenland/config/layers/Biology/Vegetation/vegetation_map.py
Add layer from the Raster Circumpolar Arctic Vegetation Map produced by [Raynolds et al., 2019](https://www.sciencedirect.com/science/article/pii/S0034425719303165?via%3Dihub#s0095).
The data came with a csv file mapping raster data values to categories and descriptions of those categories. The included style (`arctic_vegetation.qml`) labels each entry appropriately. Moreover, I  tried to match the colors used in the publication as closely as possible, by extracting color codes from this jpg: https://ars.els-cdn.com/content/image/1-s2.0-S0034425719303165-gr1_lrg.jpg
I also included mapping of raster data values to categories in the layer description for quick reference.
> Arctic vegetation cover

- .github/workflows/test-and-build.yml
- Dockerfile
- docker-compose.dev.yml
- docker-compose.yml
- qgreenland/constants/project.py
- qgreenland/util/command.py
Build and publish docker images with GH Actions to GHCR and DockerHub
This entails some other changes; for example, we were always mounting code into containers with volumes. Now, we should have the correct version of the code baked in to the container.
Fixes #542 , fixes #564
> Publish docker image to GHCR and DockerHub

- CHANGELOG.md
- qgreenland/config/cfg-lock.json
- qgreenland/config/helpers/layers/streams_outlets_basins.py
The description was incorrectly hard-coded for all hydrologic outlet/basins layers except "Ice outlets".
Apply descriptions in existing layer params dict to each layer object. :man_facepalming: 
> Fixup hydrologic outlets/basins layers descriptions

- doc/contributor/how-to/run-qgreenland.md
- docker-compose.yml
- qgreenland/constants/project.py
- qgreenland/util/edl.py
This is a good practice to avoid namespace conflicts and to make configration easier to debug.
Resolves #668 
> Prefix all envvars our code/deployment cares about with `QGREENLAND_`

- qgreenland/models/config/layer.py
> Add a list of allowed fonts and corresponding style validator

- .github/pull_request_template.md
REPLACE ME WITH A PULL REQUEST DESCRIPTION. <-- this is being replaced with more descriptive text.
> Update PR template to improve descriptiveness, add some new requirements

- qgreenland/util/qgis/project.py
Title. Closes #613 .
checkbox.
> Add title, author, and abstract to project metadata.

- .github/pull_request_template.md
- CHANGELOG.md
- qgreenland/_typing.py
- qgreenland/constants/misc.py
- qgreenland/models/config/asset.py
- qgreenland/test/util/config/test_config_export.py
- qgreenland/test/util/test_misc.py
- qgreenland/util/config/export.py
- qgreenland/util/layer.py
Title. Related to #655.
The handling of the term "online" is a bit messy. For example, we have a function called `vector_or_raster` that is typed to return one of "Raster", "Vector", or "Online", but our mapping from provider -> layer type doesn't include "Online", so `vector_or_raster` will only return what its function name indicates - "Vector" or "Raster".
The only place we appear to use the "Online" `QgsLayerType` is in the export code that produces the layer csv. This puts "Online" in the "Vector or Raster" column for online layers! That seems confusing. Maybe a separate field for "On disk" that is true/false would be a better indicator. Online assets are still either vectors or rasters!
This PR takes one step in the right direction by cleaning up OBE references to `gdal_remote` …
> Cleanup OBE references to `gdal_remote` and "Online" QgsLayerType

- qgreenland/util/qgis/project.py
Buffer the copyright text in the lower-right hand corner. Closes #652 
Uses the default buffer, which we commonly use for labeled vector features.
checkbox.
> Buffer copyright text

- doc/citing.md
- doc/conf.py
- environments/main/conda-lock.yml
- environments/main/environment.yml
- pyproject.toml
> Use Myst substitution extension to populate version in citation text

- doc/user/how-to/adding-data.md
- doc/user/how-to/metadata.md
- doc/user/how-to/online-layers.md
- doc/user/how-to/troubleshooting.md
- doc/user/tutorials/interacting-with-geospatial-data.md
title
Partially addresses #701 
checkbox.
> Update how-tos for v3

- CHANGELOG.md
- qgreenland/ancillary/styles/racmo_wind_vectors.qml
Update RACMO wind vectors style: remove color coding for magnitude
Magnitude is represented by the size of the vector lines. The color mapping was
causing conflicts with other layers (like the raster of annual wind speed). This
problem was discovered in: https://github.com/nsidc/qgreenland/pull/749
checkbox.
> Colorless RACMO wind vectors

- qgreenland/config/cfg-lock.json
- qgreenland/config/layers/Basemaps/Internet required/__settings__.py
- qgreenland/config/layers/Basemaps/Internet required/online.py
- qgreenland/config/layers/Basemaps/__settings__.py
- qgreenland/config/layers/Geology/Internet required/online.py
- qgreenland/config/layers/Geology/__settings__.py
- qgreenland/config/layers/Satellite imagery (Internet required)/__settings__.py
- qgreenland/config/layers/Satellite imagery (Internet required)/online.py
- qgreenland/config/layers/__settings__.py
- qgreenland/util/tree.py
> Re-organize internet-required layers

- qgreenland/util/qgis/project.py
> Make text style for copyright logo consistent between systems

- qgreenland/config/cfg-lock.json
- qgreenland/config/layers/Glaciology/Ice sheet velocity/GrIMP/grimp.py
changed a y to x and noted that vector layer is calculated by QGreenland Team.
checkbox.
> Update grimp.py small edits

- qgreenland/ancillary/styles/arctic_vegetation.qml
Closes #778 
Updates the vegetation legend to show raster value in each label. E.g., `B1 - Cryptogam, herb barren` to `1: B1 - Cryptogam, herb barren`
checkbox.
> Update arctic_vegetation style to show raster values in label

- qgreenland/addons-readme.txt
- qgreenland/arctic-dem-dem-only-readme.txt
- qgreenland/arctic-dem-full-package-readme.txt
This PR is to aid in the review of READMEs for the arctic dem addon packages.
Packages live here: https://data.pgc.umn.edu/gis/packages/qgreenland/packages/addons/
checkbox.
> READMEs for arctic dem add-on

- doc/user/reference/index.rst
Fixup issue with "addons" not showing up on the user ref index page.
checkbox.
> Add "addons" index to ref index listing

- doc/contributor/how-to/release-new-version.md
> Update release docs to reflect usage of new version of bumpversion

- doc/contributor/reference/data-compatibility-guide.md
- doc/user/discussion/what-is-next-qgreenland.md
Title. 
Closes #753. Closes #680 
checkbox.
> Improve documentation around preparing for QGreenland-Net
